config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  match '/fetch_pictures' => 'home#fetch_pictures', :as => :fetch_pictures, via: [:get]
  match '/about' => 'home#about', :as => :about, via: [:get]
  match '/contact' => 'home#contact', :as => :contact, via: [:get]

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def fetch_pictures
    source = "https://api.flickr.com/services/feeds/photos_public.gne?format=json"
    resp = Net::HTTP.get_response(URI.parse(source))
    data = resp.body
    data.gsub!("jsonFlickrFeed(","")
    data = data.split(")")
    data = data.join(")")
    json_val = JSON.parse data
    items = json_val["items"]
    @img_src = []
    items.each do |item|
      @img_src << item["media"]["m"]
    end
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<div class="jumbotron container">
  <div class="page-header bold"><h2 class="bold">About</h2></div>
  <div class="has-below">
    <h4 class="text-center has-below bold">Flipped is a very simple game. Following are the rules</h4>
    <ul class="text-left">
      <li>Initially you will be shown 9 images</li>
      <li>Now you have 15 seconds to remember the images</li>
      <li>After 15 seconds, images will flip and you will be shown one by one image in a random order</li>
      <li>Now you need to click on the original position of the image</li>
    </ul>
  </div>
</div>

app/views/home/contact.html.erb
<div class="jumbotron container">
  <div class="page-header"><h2>Contact Me @</h2></div>
  <div class="has-below">
  <h2 class="bold"><a href="mailto:souman.121@gmail.com" target="_top">souman.121@gmail.com</a></h2>
  </div>
</div>

app/views/home/fetch_pictures.js.erb
<% for i in 1..9 %>
  jQuery("#flipped-img<%= i.to_s %> .original_image").attr("src", "<%= j @img_src[i] %>");
  jQuery("#flipped-img<%= i.to_s %> .original_image").attr("height", "<%= j @img_src[i] %>");
<% end %>

var js_array = [<%= raw @img_src.to_json %>];

app/views/home/index.html.erb
<div class="container xyz">
  <div class="starter-template">
    <h2 id="header-text" class="text-center">Loading images...</h2>
    <div class="row row-sample hide">
      <h3 class="text-center">Click on the correct position of the image</h3>
      <div class="col-md-4 col-xs-4 col-md-offset-4 col-xs-offset-4">
        <div class="abc"><img class="sample_image" ></div>
      </div>
    </div>
  <div class="row">
    <div class="col-md-4 col-xs-4"><div class="abc" id="flipped-img1" data-index="1"><div id="test" class="dummy_image hide"></div><img class="original_image" ></div></div>
    <div class="col-md-4 col-xs-4"><div class="abc" id="flipped-img2" data-index="2"><div class="dummy_image hide"></div><img class="original_image" ></div></div>
    <div class="col-md-4 col-xs-4"><div class="abc" id="flipped-img3" data-index="3"><div class="dummy_image hide"></div><img class="original_image" ></div></div>
  </div>
  <div class="row">
    <div class="col-md-4 col-xs-4"><div class="abc" id="flipped-img4" data-index="4"><div class="dummy_image hide"></div><img class="original_image" ></div></div>
    <div class="col-md-4 col-xs-4"><div class="abc" id="flipped-img5" data-index="5"><div class="dummy_image hide"></div><img class="original_image" ></div></div>
    <div class="col-md-4 col-xs-4"><div class="abc" id="flipped-img6" data-index="6"><div class="dummy_image hide"></div><img class="original_image" ></div></div>
  </div>
  <div class="row">
    <div class="col-md-4 col-xs-4"><div class="abc" id="flipped-img7" data-index="7"><div class="dummy_image hide"></div><img class="original_image" ></div></div>
    <div class="col-md-4 col-xs-4"><div class="abc" id="flipped-img8" data-index="8"><div class="dummy_image hide"></div><img class="original_image" ></div></div>
    <div class="col-md-4 col-xs-4"><div class="abc" id="flipped-img9" data-index="9"><div class="dummy_image hide"></div><img class="original_image" ></div></div>
  </div>
  <div class="dummy_container hide" data-foo=""></div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
<script type="text/javascript">
  var currentIndex = 0;
  var alreadyFound = [];
  var statDate;
  var endDate;
  var hideOriginal = function(){
    jQuery(".original_image").addClass("hide");
    jQuery(".dummy_image").removeClass("hide");
  };
  var setCountDn = function(){
    jQuery("#header-text").html("You have <span id='counter' class='red'>15</span> seconds to remember the images");
    countdown(15);
  };

  jQuery(".dummy_image").on('click', function(){
    var imgIndex = jQuery(this).parent().data("index");
    if(imgIndex == currentIndex){
      jQuery(this).parent().find(".original_image").removeClass("hide");
      jQuery(this).addClass("hide");
      showSample();
    }
  });

  jQuery(document).ready(function() {
    jQuery.ajax({
      url: "<%= fetch_pictures_path %>",
      type: "GET",
      complete: function(){
        setTimeout(setCountDn, 1000);
        setTimeout(hideOriginal, 16000);
      }
    });
    jQuery(".original_image").height(jQuery(jQuery(".original_image")[0]).width());
    jQuery(".dummy_image").height(jQuery(jQuery(".original_image")[0]).width());
    jQuery(".sample_image").height(jQuery(jQuery(".original_image")[0]).width());
  });

  var countdown = function(seconds) {
    function tick() {
        //This script expects an element with an ID = "counter". You can change that to what ever you want. 
        var counter = document.getElementById("counter");
        counter.innerHTML = String(seconds);
        seconds--;
        if( seconds >= 0 ) {
            setTimeout(tick, 1000);
        }
        else{
          jQuery(".row-sample").removeClass("hide");
          jQuery("#header-text").addClass("hide");
          showSample();
          statDate = new Date().getTime();
        }
    }
    tick();
  }

  var showSample = function(){
    if (alreadyFound.length == 9){
      endDate = new Date().getTime();
      var timeDiff = (endDate - statDate)/1000;
      alert("Congrats!!! You have found all the images in "+timeDiff+" seconds. Click Ok to start a fresh game");
      location.reload();
      return;
    }
    while (1) {
     currentIndex = Math.floor(Math.random() * 9) + 1;
     if(jQuery.inArray(currentIndex, alreadyFound) == -1){
      alreadyFound.push(currentIndex);
      break;
     }
    }
    jQuery(".row-sample img").attr("src", js_array[0][currentIndex]);
  }
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flipped</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Flipped</a>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/about">About</a></li>
        <li><a href="/contact">Contact</a></li>
      </ul>
    </div>
  </div>
</nav>
<%= yield %>

</body>
</html>